### ISSUE TITLE
ENVI-MET and MORPHO

### ISSUE THREAD

**Issue by fish0920** [AntonelloDN/Morpho#1]
hi Antonello,
    I would like to ask you some question about ENVI-MET and MORPHO .The soil surface established in Morpho cannot be transformed into the soil material in the ENVI-MET  model but building is ok. You could check out my appendix file .I have no way to solve it, I hope you can help me.Thank you very much.  In addition  ,I'm using Rhino6 version and the latest Morpho battery string, but I downloaded Morpho before, so I just replaced the latest version of GHuser with nothing else, and I don't know how to uninstall and reinstall Morpho.
     Best wishes to you .thanks
                                                                                                            by fish0920lhy

**Comment by AntonelloDN** [comment]
Hi @fish0920, I close this issue because I think it is because of the normal vector. I have added a nice description about it here: [Rhino mapping](https://github.com/AntonelloDN/Morpho/wiki/1.-Grasshopper-plugin#geometry-mapping). If it is not you can reopen this issue
