### ISSUE TITLE
1. Solution exception:WindowsError

### ISSUE THREAD

**Issue by andreabotti** [AntonelloDN/Morpho#13]
Hi @AntonelloDN ,
the update to Morpho 1.0.3 failed on one of my PCs.
Upon execution of the `install_lib.gh`, I get the following error:

```
Runtime error (Win32Exception): WindowsError
Traceback:
  line 273, in rmtree, "C:\Program Files\Rhino 7\Plug-ins\IronPython\Lib\shutil.py"
  line 249, in onerror, "C:\Program Files\Rhino 7\Plug-ins\IronPython\Lib\shutil.py"
  line 275, in rmtree, "C:\Program Files\Rhino 7\Plug-ins\IronPython\Lib\shutil.py"
  line 62, in script
```
any idea of what this may depend upon?

**Comment by AntonelloDN** [comment]
Hi @andreabotti, it can be related to IO privileges. I should evaluate if it is a good moment to build an installer.

**Comment by AntonelloDN** [comment]
Hi @andreabotti, can you try the `Morpho.Rhino.Installer` of [release v1.3.0](https://github.com/AntonelloDN/Morpho/releases/tag/v1.3.0)?

**Comment by andreabotti** [comment]
> Hi @andreabotti, can you try the `Morpho.Rhino.Installer` of [release v1.3.0](https://github.com/AntonelloDN/Morpho/releases/tag/v1.3.0)?

I checked and it works well!
