### ISSUE TITLE
Color and dynamic wind representation

### ISSUE THREAD

**Issue by frank11000** [AntonelloDN/Morpho#2]
![Capture](https://user-images.githubusercontent.com/46491082/113573011-95697f80-9619-11eb-8841-a4c329cafa7d.JPG)

Hi Antonello,

I'm Frank, stutend at the French Sorbonne University, working on construction methods for reduction heat impact on my thesis.

First I'd like to express my admiration for your work on the LadyBug and Morpho Plugins, it's amazing tools.

As you can see in the picture, I manage to represent the wind direction (arrows direction) and the wind speed (arrows size).

Do you know if it is possible to reprensent the wind speed with different colors ?

Do you know if it's possible to represent dynamically the wind direction with a short animation showing the air path ?

Frank
frankforster75@gmail.com

**Comment by AntonelloDN** [comment]
Hi @frank11000,

Thanks. 
You can apply color to arrows in many ways, for example using the colors from air temperature or using the wind speed and so on. I have added a new example file about arrows color [09_results_wind_speed_vectors](https://github.com/AntonelloDN/Morpho/tree/master/examples/grasshopper).

About dynamic visualization, I tested only with heatmaps and GIF. I think it would be possible to shows air path but It will require a bit of coding or another kind of workflow.
