### ISSUE TITLE
Add environment soils

### ISSUE THREAD

**Issue by Gyf0** [AntonelloDN/Morpho#22]
Hello, 

I'm having a problem with adding environment soils. I followed the step in 1.1.3 but when I check the model in envimet I can't find the soil I set, the material shows all 00. What might be wrong and how can I solve it?

Thanks a lot! 
![IMG_8175](https://github.com/AntonelloDN/Morpho/assets/153727446/7dac0431-ee15-46e2-8c07-3b5280ca99a1)
![IMG_8176](https://github.com/AntonelloDN/Morpho/assets/153727446/49ca3e0e-6499-4e25-a339-bc8dc6bd3325)
![IMG_8177](https://github.com/AntonelloDN/Morpho/assets/153727446/6a2d62ad-947a-43fd-815f-2e7189291137)

**Comment by AntonelloDN** [comment]
Hi @Gyf0, can you connect inx_soil output directly to Model component?

**Comment by Gyf0** [comment]
> Hi @Gyf0, can you connect inx_soil output directly to Model component?
> 
> 你好@gy f0，你能把 inx _ soil 输出直接连接到 Model 组件吗？

It works! Now it shows in envimet. Thanks a lot.
