### ISSUE TITLE
Plant 3D

### ISSUE THREAD

**Issue by frank11000** [AntonelloDN/Morpho#4]
Hello,

I have some 3D plants in my ENVI-MET .INX files.

I managed to see the buildings with MORPHO-EnviMetDisplay but I can't find a way to display the 3D plants.

Do you know if that's possible ?

Thanks,

Frank

**Comment by AntonelloDN** [comment]
Hi @frank11000, there is not a preview component about plants for now. You can display them only with the reading part.
