### ISSUE TITLE
Can't run simulation

### ISSUE THREAD

**Issue by seghier** [AntonelloDN/Morpho#6]
Hello, i test this file 
`from_modeling_to_simulation.gh`
With envimet 4.4.5 work fine , when i install the version 4.4.6 and test it again i can't run simulation and this message appears

![image](https://user-images.githubusercontent.com/6026588/136632071-2eafe4da-9f4e-4a42-ad16-05695c227476.png)

**Comment by AntonelloDN** [comment]
@seghier, it is updated to envimet 5 now. Could you test it? Thanks
