### ISSUE TITLE
read pollution edt

### ISSUE THREAD

**Issue by idheitmann** [AntonelloDN/Morpho#9]
slice read currently does not support pollution results, please add this function

**Comment by AntonelloDN** [comment]
Hi @idheitmann, it should be easy. Can you send/share the folder structure to use to retrieve pollution EDT/EDX files?

**Comment by idheitmann** [comment]
is this what you need?
\ENVI_MET\<workspace>\<project>\<shortname>_output\pollutants\<shortname>_POLU_yyyy-mm-dd_hh.00.01.EDX

**Comment by AntonelloDN** [comment]
@idheitmann can you check the latest release? Thanks

**Comment by idheitmann** [comment]
![image](https://user-images.githubusercontent.com/14552260/206048736-08854722-bf3d-4a5d-b874-d2d3c7dfd424.png)
The component that I need does not accept pollutant inputs still

**Comment by AntonelloDN** [comment]
Hi @idheitmann, can you [try release 1.1.0](https://github.com/AntonelloDN/Morpho/releases/tag/v1.1.0)? There is a small validation inside the component itself. I have added pollutants type.

**Comment by idheitmann** [comment]
Seems to work great so far!
